version: "3.7"
services:

  hardboiled-apache:
    image: httpd
    ports: 
      - "80:80"
      - "443:443"
    expose:
      - "443"
      - "80"
    volumes:
      - ".:/usr/local/apache2/htdocs/"
      - "./certs/:/usr/local/apache2/conf/"
      - "./logs/:/usr/local/apache2/logs/"
      